#!/usr/bin/env python3

# TODO Switch this to use a config file instead of command line options (maybe TOML)
# TODO Run as a linux deamon

import os
import sys

from Markov import Markov

# Redo the README.md

# TODO work on the sending the tweets!

if __name__ == '__main__':
    try:
        sources = ['../books/' + x for x in os.listdir('../books')]

        markov = Markov(sources)

        for message in markov.messages():
            print(message)

    except KeyboardInterrupt:
        print('Shutting down 🔽')
        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)

